// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_a3D21IOZd6tRZvDv2WACEi0Qz_ixzEI',
    appId: '1:745754582464:web:4f8b2a340cd2bae317fc25',
    messagingSenderId: '745754582464',
    projectId: 'noted-flutter-proj',
    authDomain: 'noted-flutter-proj.firebaseapp.com',
    storageBucket: 'noted-flutter-proj.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDTwxM1uRvH4fyGgKUFwVDU0NmEE3BHA8',
    appId: '1:745754582464:android:5db9692452e0c47517fc25',
    messagingSenderId: '745754582464',
    projectId: 'noted-flutter-proj',
    storageBucket: 'noted-flutter-proj.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvNs7_36CY1fer2uI08S6lKpQup1d11xs',
    appId: '1:745754582464:ios:5cba50ea880c504017fc25',
    messagingSenderId: '745754582464',
    projectId: 'noted-flutter-proj',
    storageBucket: 'noted-flutter-proj.appspot.com',
    iosBundleId: 'com.sfhdev.noted',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvNs7_36CY1fer2uI08S6lKpQup1d11xs',
    appId: '1:745754582464:ios:6594ca8b6ce04fe417fc25',
    messagingSenderId: '745754582464',
    projectId: 'noted-flutter-proj',
    storageBucket: 'noted-flutter-proj.appspot.com',
    iosBundleId: 'com.sfhdev.noted.RunnerTests',
  );
}
